### ISSUE TITLE
Vagrant run Example not fully working

### ISSUE THREAD

**Issue by SomeStrangeName** [ewolff/user-registration-V2#4]
Looks like the localhost:18081 is not reachable after running vagrant up in shell folder as requested in the book on page 34.

If I look into the tomcat7 log (in vm) it see following errors:

```
2016-11-20 20:59:37.794  INFO 1546 --- [ost-startStop-1] egistrationApplicationServletInitializer : Started RegistrationApplicationServletInitializer in 16.857 seconds (JVM running for 24.852)
Nov 20, 2016 8:59:37 PM org.apache.catalina.core.ContainerBase addChildInternal
SEVERE: ContainerBase.addChild: start:
org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/user-registration-application-0.0.1-SNAPSHOT]]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:154)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:649)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1083)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1879)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: javax.servlet.ServletContext.getVirtualServerName()Ljava/lang/String;
        at org.apache.tomcat.websocket.server.WsServerContainer.<init>(WsServerContainer.java:150)
        at org.apache.tomcat.websocket.server.WsSci.init(WsSci.java:131)
        at org.apache.tomcat.websocket.server.WsSci.onStartup(WsSci.java:47)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5481)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        ... 10 more

Nov 20, 2016 8:59:37 PM org.apache.catalina.startup.HostConfig deployWAR
SEVERE: Error deploying web application archive /var/lib/tomcat7/webapps/user-registration-application-0.0.1-SNAPSHOT.war
java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/user-registration-application-0.0.1-SNAPSHOT]]
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:904)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:649)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1083)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1879)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

Nov 20, 2016 8:59:37 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deployment of web application archive /var/lib/tomcat7/webapps/user-registration-application-0.0.1-SNAPSHOT.war has finished in 23,305 ms
Nov 20, 2016 8:59:37 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory /var/lib/tomcat7/webapps/ROOT
Nov 20, 2016 8:59:38 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deployment of web application directory /var/lib/tomcat7/webapps/ROOT has finished in 513 ms
Nov 20, 2016 8:59:38 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-bio-8080"]
Nov 20, 2016 8:59:38 PM org.apache.catalina.startup.Catalina start
INFO: Server startup in 23986 ms

```

I guess this is not by intention.

Could it be the war in the shell folder is build with the wrong java version?

**Comment by ewolff** [comment]
Thanks for spotting this! I fixed it. Sorry for the hassle! Please reopen if the problem persists.

**Comment by SomeStrangeName** [comment]
After deleting the vm with vagrant destroy and rebuilding it with vagrant up the example seems working.

**Comment by ewolff** [comment]
Excellent - thanks for trying it out and reporting the bug! :-)

**Comment by SomeStrangeName** [comment]
Could it be there is the same issue with the chef example and the demo.war in user-registration-V2/chef/cookbooks/webapp/files/default?

**Comment by ewolff** [comment]
I'll have a look.

**Comment by ewolff** [comment]
Should work now - thanks a lot again for spotting this!
